### ISSUE TITLE
书本第七章的单元测试疑似出现方法名写错的情况

### ISSUE THREAD

**Issue by JayceTsien** [xiuhuai/Spring-Boot-Book#1]
https://github.com/xiuhuai/Spring-Boot-Book/blob/8492be23656fdb54bfcf78e418a5428f6217e5a3/07/UnitTestDemoJpaTest/src/test/java/com/example/demo/repository/CardRepositoryTest.java#L49

此处的`testRollBank`应该是`testRollBack`，请老师检查一下，书本前几页也有类似同样的`testRollBank`的方法名

**Comment by xiuhuai** [comment]
收到您的指正，非常感谢您，谢谢。
