### ISSUE TITLE
第15章的案例资源中少了js部分的资源？

### ISSUE THREAD

**Issue by ygl2020** [xiuhuai/Spring-Boot-Book#4]
第15章的案例资源中少了js部分的资源？

**Comment by xiuhuai** [comment]
因为此实例具有很强的扩展性，所以只演示了核心功能，并不是完整的项目。再加上作者使用了收费版的layui，因为版权问题，所以不能提供相关的静态文件，如果需要建议去layui下载，请知悉。

**Comment by ygl2020** [comment]
明白了，谢谢
